theme: jekyll-theme-cayman
title: Welcome to SafeBet
description: SafeBet is a research project in Ulster University focussing on creating algorithms that rapidly detect online peer-to-peer gambling fraud through DeepTech that analyses and aggregates individual in-game patterns, trends and behaviours for multi-player games.
github: is_project_page: false
